version: 0.2

phases:
    install:
        runtime-version:
            nodejs: latest
        commands:
            - echo "Installing something."
    pre_build:
        commands:
            - echo "We are in the pre-build:phase." 
    build:
        commands:
            - echo "We are in the build block."
            - echo "We will build something."
            - grep -Fq "second" ./public/index.html
    post_build:
        commands:
            - echo "We are in the post build phase."
    